name: Merge on Release

on:
  release:
    types:
      - created

env:
  SOURCE_BRANCH: develop
  TARGET_BRANCH: main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.AUTOMERGER_PAT }}

      - name: Merge source branch into target branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git checkout ${{ env.TARGET_BRANCH }}
          git merge --squash --no-edit origin/${{ env.SOURCE_BRANCH }}
          git commit -m "chore: release from ${{ env.SOURCE_BRANCH }} to ${{ env.TARGET_BRANCH }}"
          git push origin ${{ env.TARGET_BRANCH }}
